version: '3'
services:
 api:
   build: src
   ports:
     - ${API_PORT}:${API_PORT}
   volumes:
     - .:/code
   command: flask run --host=${API_HOST} --port=${API_PORT}

 front:
   build: front
   volumes:
     - ./front:/front
     - /front/node_modules
   environment:
     - FRONT_HOST=${FRONT_HOST}
     - NODE_ENV=${NODE_ENV}
   ports:
     - 8080:8080
   depends_on:
     - api
